apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bjqrvvk1u-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:0cd8e0892746a8a3c74f009e60caea3c387167f9@sha256:84f1e84587f752b838b1aeecdae89b6ff88a315ecf6a5bb66fc926d7612915d8
          name: container-image
